In [1]:
import pandas as pd
import numpy as np
import warnings
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score



In [2]:
# Suppress the warning message
warnings.filterwarnings("ignore", message="X does not have valid feature names")

# Load the dataset
df = pd.read_csv("data/check.csv")

# Extract the features and target variable
X = df[['win_rate']]
y = df['bot_decision']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a decision tree classifier
model_DT = DecisionTreeClassifier()

# Fit the classifier to the training data
model_DT.fit(X_train, y_train)

# Predict the target variable on the testing data
y_pred = model_DT.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7869166666666667


In [3]:


# Load the dataset
df = pd.read_csv("data/check.csv")

# Extract the features and target variable
X = df[['win_rate']]
y = df['bot_decision']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a random forest classifier with 100 trees
model_RF = RandomForestClassifier(n_estimators=100)

# Fit the classifier to the training data
model_RF.fit(X_train, y_train)

# Predict the target variable on the testing data
y_pred = model_RF.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.7870833333333334


In [4]:
# Create a 1D NumPy array with 10 random float values between 0 and 1
random_floats = np.random.rand(30)

# Sort the array in ascending order
sorted_floats = np.sort(random_floats)

# Reshape the sorted array into a 2D array with one column
new_data = sorted_floats.reshape(-1, 1)

# Make predictions on the new data using the trained model
predictions_DT = model_DT.predict(new_data)

# Make predictions on the new data using the trained model
predictions_RF = model_RF.predict(new_data)

print(sorted_floats)
print(predictions_DT)
print(predictions_RF)

[0.06285829 0.12811724 0.22183655 0.24437166 0.24545332 0.24694864
 0.25228566 0.28918263 0.40883215 0.41514769 0.46576561 0.47273628
 0.53905681 0.59853303 0.61271249 0.6132667  0.6175442  0.63350294
 0.63863236 0.64239915 0.67822438 0.70803895 0.74680806 0.76927958
 0.83075194 0.83431384 0.88163482 0.89904731 0.91493294 0.99410676]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 0 0]


In [5]:
# Load the data from the CSV file
df = pd.read_csv("data/raise.csv")

# Split the data into training and test sets
X = df[['win_rate', 'pot', 'player_raise_amount']]
y = df['bot_decision']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a random forest classifier object
model_raise = RandomForestClassifier()

# Fit the classifier to the training data
model_raise.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model_raise.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy
print("Accuracy:", accuracy)


Accuracy: 0.79485


In [6]:
# Create a 1D NumPy array with 10 random float values between 0 and 1
random_floats = np.random.rand(20)

# Sort the array in ascending order
sorted_floats = np.sort(random_floats)

# Create a numpy array with 20 random integers between 0 and 40000
arr = np.random.randint(low=0, high=40001, size=20)

arr2=np.random.randint(low=0, high=301, size=20)

# Create a Pandas DataFrame with three columns
df = pd.DataFrame({'win_rate': sorted_floats, 'pot': arr, 'player_raise_amount': arr2})

# Print the DataFrame
print(df)
# Make predictions on the new data using the trained model
predictions_raise = model_raise.predict(df)

print(predictions_raise)


    win_rate    pot  player_raise_amount
0   0.060626  36897                   58
1   0.129060  21871                   69
2   0.194287  39232                  224
3   0.221680  17744                  290
4   0.247899  22909                   70
5   0.330500  13736                   14
6   0.338355  29825                  223
7   0.357446  28927                  162
8   0.366726  14669                  245
9   0.389006  38902                  127
10  0.429383  29753                  236
11  0.483848  29935                  184
12  0.507532  19165                  199
13  0.564248  31718                   36
14  0.685571  31040                   25
15  0.710462   1440                  140
16  0.723647  33941                  292
17  0.769463    426                   36
18  0.792606  15944                   55
19  0.996275   5793                   71
[1 1 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 2 2]


In [7]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the dataset
df = pd.read_csv("data/raise_amount.csv")

# Extract the features and target variable
X = df[['win_rate']]
y = df['bot_decision']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a random forest classifier with 100 trees
model_amount = RandomForestClassifier()

# Fit the classifier to the training data
model_amount.fit(X_train, y_train)

# Predict the target variable on the testing data
y_pred = model_amount.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.32451853981029033


In [8]:
# Create a 1D NumPy array with 10 random float values between 0 and 1
random_floats = np.random.rand(30)

# Sort the array in ascending order
sorted_floats = np.sort(random_floats)

# Reshape the sorted array into a 2D array with one column
new_data = sorted_floats.reshape(-1, 1)

# Make predictions on the new data using the trained model
predictions_amount = model_amount.predict(new_data)


print(sorted_floats)
predictions_amount

[9.32447542e-04 1.28740542e-01 1.59120375e-01 2.12573714e-01
 2.27107546e-01 3.11192321e-01 3.19156126e-01 3.35837292e-01
 3.61256710e-01 3.86830458e-01 4.09297748e-01 4.59498358e-01
 4.78867624e-01 5.68037629e-01 5.86089063e-01 6.22608010e-01
 6.34610562e-01 6.47643472e-01 6.87417225e-01 6.96019470e-01
 7.71405520e-01 7.92648133e-01 8.05072008e-01 8.88580695e-01
 9.00494338e-01 9.08051940e-01 9.17851230e-01 9.26742179e-01
 9.28379788e-01 9.50775291e-01]


array([3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 2, 0, 0, 0, 2, 1, 0, 0, 1, 3,
       3, 1, 1, 1, 0, 1, 2, 2], dtype=int64)